package Pojo;
// Generated 01-jul-2017 17:29:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ControlEmbarazada generated by hbm2java
 */
public class ControlEmbarazada  implements java.io.Serializable {


     private Integer idControl;
     private Embarazada embarazada;
     private Date fecha;
     private String observacion;

    public ControlEmbarazada() {
    }

    public ControlEmbarazada(Embarazada embarazada, Date fecha, String observacion) {
       this.embarazada = embarazada;
       this.fecha = fecha;
       this.observacion = observacion;
    }
   
    public Integer getIdControl() {
        return this.idControl;
    }
    
    public void setIdControl(Integer idControl) {
        this.idControl = idControl;
    }
    public Embarazada getEmbarazada() {
        return this.embarazada;
    }
    
    public void setEmbarazada(Embarazada embarazada) {
        this.embarazada = embarazada;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


