package Pojo;
// Generated 01-jul-2017 17:29:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DetalleEnfermedadCronica generated by hbm2java
 */
public class DetalleEnfermedadCronica  implements java.io.Serializable {


     private int idDetalleEnfermedadCronica;
     private EnfermedadCronica enfermedadCronica;
     private Paciente paciente;
     private Date fechaDiagnostico;

    public DetalleEnfermedadCronica() {
    }

	
    public DetalleEnfermedadCronica(int idDetalleEnfermedadCronica) {
        this.idDetalleEnfermedadCronica = idDetalleEnfermedadCronica;
    }
    public DetalleEnfermedadCronica(int idDetalleEnfermedadCronica, EnfermedadCronica enfermedadCronica, Paciente paciente, Date fechaDiagnostico) {
       this.idDetalleEnfermedadCronica = idDetalleEnfermedadCronica;
       this.enfermedadCronica = enfermedadCronica;
       this.paciente = paciente;
       this.fechaDiagnostico = fechaDiagnostico;
    }
   
    public int getIdDetalleEnfermedadCronica() {
        return this.idDetalleEnfermedadCronica;
    }
    
    public void setIdDetalleEnfermedadCronica(int idDetalleEnfermedadCronica) {
        this.idDetalleEnfermedadCronica = idDetalleEnfermedadCronica;
    }
    public EnfermedadCronica getEnfermedadCronica() {
        return this.enfermedadCronica;
    }
    
    public void setEnfermedadCronica(EnfermedadCronica enfermedadCronica) {
        this.enfermedadCronica = enfermedadCronica;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Date getFechaDiagnostico() {
        return this.fechaDiagnostico;
    }
    
    public void setFechaDiagnostico(Date fechaDiagnostico) {
        this.fechaDiagnostico = fechaDiagnostico;
    }




}


