package Pojo;
// Generated 01-jul-2017 17:29:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Embarazada generated by hbm2java
 */
public class Embarazada  implements java.io.Serializable {


     private Integer idEmbarazada;
     private Paciente paciente;
     private Date fechaEntrada;
     private Date fechaPeriodo;
     private Date fechaParto;
     private Set controlEmbarazadas = new HashSet(0);

    public Embarazada() {
    }

    public Embarazada(Paciente paciente, Date fechaEntrada, Date fechaPeriodo, Date fechaParto, Set controlEmbarazadas) {
       this.paciente = paciente;
       this.fechaEntrada = fechaEntrada;
       this.fechaPeriodo = fechaPeriodo;
       this.fechaParto = fechaParto;
       this.controlEmbarazadas = controlEmbarazadas;
    }
   
    public Integer getIdEmbarazada() {
        return this.idEmbarazada;
    }
    
    public void setIdEmbarazada(Integer idEmbarazada) {
        this.idEmbarazada = idEmbarazada;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public Date getFechaPeriodo() {
        return this.fechaPeriodo;
    }
    
    public void setFechaPeriodo(Date fechaPeriodo) {
        this.fechaPeriodo = fechaPeriodo;
    }
    public Date getFechaParto() {
        return this.fechaParto;
    }
    
    public void setFechaParto(Date fechaParto) {
        this.fechaParto = fechaParto;
    }
    public Set getControlEmbarazadas() {
        return this.controlEmbarazadas;
    }
    
    public void setControlEmbarazadas(Set controlEmbarazadas) {
        this.controlEmbarazadas = controlEmbarazadas;
    }




}


