package Pojo;
// Generated 01-jul-2017 17:29:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EnfermedadCronica generated by hbm2java
 */
public class EnfermedadCronica  implements java.io.Serializable {


     private Integer idEnfermedad;
     private String nombre;
     private Set detalleEnfermedadCronicas = new HashSet(0);

    public EnfermedadCronica() {
    }

    public EnfermedadCronica(String nombre, Set detalleEnfermedadCronicas) {
       this.nombre = nombre;
       this.detalleEnfermedadCronicas = detalleEnfermedadCronicas;
    }
   
    public Integer getIdEnfermedad() {
        return this.idEnfermedad;
    }
    
    public void setIdEnfermedad(Integer idEnfermedad) {
        this.idEnfermedad = idEnfermedad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDetalleEnfermedadCronicas() {
        return this.detalleEnfermedadCronicas;
    }
    
    public void setDetalleEnfermedadCronicas(Set detalleEnfermedadCronicas) {
        this.detalleEnfermedadCronicas = detalleEnfermedadCronicas;
    }




}


