package Pojo;
// Generated 01-jul-2017 17:29:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medicamento generated by hbm2java
 */
public class Medicamento  implements java.io.Serializable {


     private Integer idMedicamento;
     private String nombre;
     private Date fechaVencimiento;
     private String tipo;
     private Set planificacions = new HashSet(0);
     private Set detalleConsultas = new HashSet(0);

    public Medicamento() {
    }

    public Medicamento(String nombre, Date fechaVencimiento, String tipo, Set planificacions, Set detalleConsultas) {
       this.nombre = nombre;
       this.fechaVencimiento = fechaVencimiento;
       this.tipo = tipo;
       this.planificacions = planificacions;
       this.detalleConsultas = detalleConsultas;
    }
   
    public Integer getIdMedicamento() {
        return this.idMedicamento;
    }
    
    public void setIdMedicamento(Integer idMedicamento) {
        this.idMedicamento = idMedicamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getPlanificacions() {
        return this.planificacions;
    }
    
    public void setPlanificacions(Set planificacions) {
        this.planificacions = planificacions;
    }
    public Set getDetalleConsultas() {
        return this.detalleConsultas;
    }
    
    public void setDetalleConsultas(Set detalleConsultas) {
        this.detalleConsultas = detalleConsultas;
    }




}


