package Pojo;
// Generated 01-jul-2017 17:29:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by hbm2java
 */
public class Medico  implements java.io.Serializable {


     private Integer idMedico;
     private Personal personal;
     private String cargo;
     private String departemento;
     private String especialidad;
     private Set consultas = new HashSet(0);

    public Medico() {
    }

    public Medico(Personal personal, String cargo, String departemento, String especialidad, Set consultas) {
       this.personal = personal;
       this.cargo = cargo;
       this.departemento = departemento;
       this.especialidad = especialidad;
       this.consultas = consultas;
    }
   
    public Integer getIdMedico() {
        return this.idMedico;
    }
    
    public void setIdMedico(Integer idMedico) {
        this.idMedico = idMedico;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getDepartemento() {
        return this.departemento;
    }
    
    public void setDepartemento(String departemento) {
        this.departemento = departemento;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


