package Pojo;
// Generated 01-jul-2017 17:29:13 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import Model.PacientModel;
import Pojo.Paciente;

/**
 * Paciente generated by hbm2java
 */
public class Paciente implements java.io.Serializable {

    private Integer idPaciente;
    private String numeroExpediente;
    private String nombre;
    private String apellido;
    private Date fechaNacimiento;
    private String cedula;
    private String sexo;
    private String segundoNombre;
    private String segundoApellido;
    private Set embarazadas = new HashSet(0);
    private Set planificacions = new HashSet(0);
    private Set paps = new HashSet(0);
    private Set detalleEnfermedadCronicas = new HashSet(0);

    public Paciente() {
    }

    public Paciente(String numeroExpediente, String nombre, String apellido, Date fechaNacimiento, String cedula, String sexo, String segundoNombre, String segundoApellido, Set embarazadas, Set planificacions, Set paps, Set detalleEnfermedadCronicas) {
        this.numeroExpediente = numeroExpediente;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNacimiento = fechaNacimiento;
        this.cedula = cedula;
        this.sexo = sexo;
        this.segundoNombre = segundoNombre;
        this.segundoApellido = segundoApellido;
        this.embarazadas = embarazadas;
        this.planificacions = planificacions;
        this.paps = paps;
        this.detalleEnfermedadCronicas = detalleEnfermedadCronicas;
    }

    public Integer getIdPaciente() {
        return this.idPaciente;
    }

    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

    public String getNumeroExpediente() {
        return this.numeroExpediente;
    }

    public void setNumeroExpediente(String numeroExpediente) {
        this.numeroExpediente = numeroExpediente;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getCedula() {
        return this.cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    public String getSexo() {
        return this.sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public String getSegundoNombre() {
        return this.segundoNombre;
    }

    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }

    public String getSegundoApellido() {
        return this.segundoApellido;
    }

    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }

    public Set getEmbarazadas() {
        return this.embarazadas;
    }

    public void setEmbarazadas(Set embarazadas) {
        this.embarazadas = embarazadas;
    }

    public Set getPlanificacions() {
        return this.planificacions;
    }

    public void setPlanificacions(Set planificacions) {
        this.planificacions = planificacions;
    }

    public Set getPaps() {
        return this.paps;
    }

    public void setPaps(Set paps) {
        this.paps = paps;
    }

    public Set getDetalleEnfermedadCronicas() {
        return this.detalleEnfermedadCronicas;
    }

    public void setDetalleEnfermedadCronicas(Set detalleEnfermedadCronicas) {
        this.detalleEnfermedadCronicas = detalleEnfermedadCronicas;
    }

    public List<Object> getPacientRecords() {

        List<Object> list = null;
        try {
            PacientModel model = new PacientModel();
            list = model.getPacientRecords();

        } catch (Exception e) {
        }

        return list;

    }

    public List<Paciente> getPacientReports() {

        List<Paciente> list = null;
        try {
            PacientModel model = new PacientModel();
            list = model.getPacientReports();

        } catch (Exception e) {
        }

        return list;

    }
}
