package Pojo;
// Generated 01-jul-2017 17:29:13 by Hibernate Tools 4.3.1



/**
 * Tecnicoenfermeria generated by hbm2java
 */
public class Tecnicoenfermeria  implements java.io.Serializable {


     private Integer idTecnicoEnfermeria;
     private Personal personal;
     private String cargo;
     private String departamento;
     private String especialidad;

    public Tecnicoenfermeria() {
    }

    public Tecnicoenfermeria(Personal personal, String cargo, String departamento, String especialidad) {
       this.personal = personal;
       this.cargo = cargo;
       this.departamento = departamento;
       this.especialidad = especialidad;
    }
   
    public Integer getIdTecnicoEnfermeria() {
        return this.idTecnicoEnfermeria;
    }
    
    public void setIdTecnicoEnfermeria(Integer idTecnicoEnfermeria) {
        this.idTecnicoEnfermeria = idTecnicoEnfermeria;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }




}


