package Pojo;
// Generated 01-jul-2017 17:29:13 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private Integer idUsuario;
    private String usuario;
    private String contrasenia;
    private String rolsistema;
    private Integer idPersonal;
    private Boolean estado;
    private Set personals = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String usuario, String contrasenia, String rolsistema, Integer idPersonal, Boolean estado, Set personals) {
        this.usuario = usuario;
        this.contrasenia = contrasenia;
        this.rolsistema = rolsistema;
        this.idPersonal = idPersonal;
        this.estado = estado;
        this.personals = personals;
    }

    public Integer getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getContrasenia() {
        return this.contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    public String getRolsistema() {
        return this.rolsistema;
    }

    public void setRolsistema(String rolsistema) {
        this.rolsistema = rolsistema;
    }

    public Integer getIdPersonal() {
        return this.idPersonal;
    }

    public void setIdPersonal(Integer idPersonal) {
        this.idPersonal = idPersonal;
    }

    public Boolean getEstado() {
        return this.estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Set getPersonals() {
        return this.personals;
    }

    public void setPersonals(Set personals) {
        this.personals = personals;
    }

    public boolean AccessSystem(Usuario user) {

        Model.LoginModel model = new Model.LoginModel();

        List list = model.SessionStart("SELECT U.usuario, U.contrasenia FROM Usuario U");

        Iterator i = list.iterator();

        while (i.hasNext()) {
            Object[] obj = (Object[]) i.next();

            if (user.getUsuario().equals(obj[0]) && user.getContrasenia().equals(obj[1])) {
                return true;
            }
        }
        return false;
    }

}
